apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: snake-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - snakedetector.ml
    - www.snakedetector.ml
    secretName: snake-tls
  rules:
  - host: snakedetector.ml
    http:
      paths:
      - path: /api/v1.0
        backend:
          serviceName: api
          servicePort: 5002
      - path: /
        backend:
          serviceName: frontend
          servicePort: 5000
  - host: www.snakedetector.ml
    http:
      paths:
      - path: /api/v1.0
        backend:
          serviceName: api
          servicePort: 5002
      - path: /
        backend:
          serviceName: frontend
          servicePort: 5000


