apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-vol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath:
    path: "/tmp/snake/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
